// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs xlsx-merge`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "csv-to-xlsx",
    "icon": "📥",
    "name": {
      "en": "CSV to XLSX",
      "ja": "CSV→XLSX統合",
      "zh": "CSV 合并为 XLSX",
      "de": "CSV zu XLSX zusammenführen",
      "es": "CSV a XLSX"
    },
    "desc": {
      "en": "Combine multiple CSV files into one Excel workbook, one sheet per file.",
      "ja": "複数CSVを1ファイル1シートで1つのExcelに統合。",
      "zh": "将多个 CSV 文件合并为一个 Excel 工作簿，一文件一工作表。",
      "de": "Führt mehrere CSV-Dateien zu einer Excel-Arbeitsmappe zusammen, ein Blatt pro Datei.",
      "es": "Combina varios archivos CSV en un libro de Excel, una hoja por archivo."
    }
  },
  {
    "slug": "compare-xlsx",
    "icon": "⚖️",
    "name": {
      "en": "Compare Excel Workbooks",
      "ja": "Excel比較",
      "zh": "比较 Excel 工作簿",
      "de": "Excel-Arbeitsmappen vergleichen",
      "es": "Comparar libros de Excel"
    },
    "desc": {
      "en": "Compare two Excel workbooks cell by cell, sheet by sheet.",
      "ja": "2つのExcelブックをシート・セル単位で比較。",
      "zh": "按工作表和单元格逐一比较两个 Excel 工作簿。",
      "de": "Vergleicht zwei Excel-Arbeitsmappen Blatt für Blatt, Zelle für Zelle.",
      "es": "Compara dos libros de Excel hoja por hoja, celda por celda."
    }
  },
  {
    "slug": "xlsx-viewer",
    "icon": "📗",
    "name": {
      "en": "Excel Workbook Viewer",
      "ja": "Excelビューア",
      "zh": "Excel 查看器",
      "de": "Excel-Arbeitsmappen-Viewer",
      "es": "Visor de libros de Excel"
    },
    "desc": {
      "en": "Open and browse an Excel workbook: switch sheets, no editing.",
      "ja": "Excelブックを開いて閲覧。シート切替、編集はしません。",
      "zh": "打开并浏览 Excel 工作簿，可切换工作表，不支持编辑。",
      "de": "Excel-Arbeitsmappe öffnen und ansehen, Blätter wechseln, keine Bearbeitung.",
      "es": "Abre y consulta un libro de Excel, cambia de hoja, sin edición."
    }
  },
  {
    "slug": "strip-xlsx-metadata",
    "icon": "🧹",
    "name": {
      "en": "Strip XLSX Metadata",
      "ja": "Excelメタデータ削除",
      "zh": "清除 Excel 元数据",
      "de": "XLSX-Metadaten entfernen",
      "es": "Eliminar metadatos de XLSX"
    },
    "desc": {
      "en": "Remove author, company, and custom-property metadata from an Excel workbook.",
      "ja": "Excelブックの作成者・会社名・カスタムプロパティを削除。",
      "zh": "移除 Excel 工作簿中的作者、公司和自定义属性等元数据。",
      "de": "Entfernt Autor-, Firmen- und benutzerdefinierte Metadaten aus einer Excel-Arbeitsmappe.",
      "es": "Elimina el autor, la empresa y las propiedades personalizadas de un libro de Excel."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'xlsx-merge';
